name: Build TikTokPro Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install ldid xz

      # -- تم تعديل هذه الخطوة --
      - name: Install Theos & Specific SDK
        run: |
          # 1. تحميل Theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          # 2. تحميل نسخة SDK مستقرة (iOS 16.4) من مصدر بديل
          curl -LO https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS16.5.sdk.tar.xz
          # 3. فك ضغط الـ SDK
          tar -xf iPhoneOS16.5.sdk.tar.xz -C $THEOS/sdks/
      - name: Debug File Structure and Makefile
        run: |
        echo "--- Verifying file structure ---"
          ls -R
       echo "--- Verifying Makefile content ---"
          cat Makefile
     - name: Build Tweak
        run: |
          make clean package

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ github.run_number }}
          release_name: Build ${{ github.run_number }}
          draft: false
          prerelease: true

      - name: Upload Tweak .deb to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /packages/*.deb
          asset_name: tiktokpro.deb
          asset_content_type: application/vnd.debian.binary-package
